version: '3.9'

services:
  web:
    build: .
    container_name: django-app
    command: >
        sh -c "python manage.py wait_for_db &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    networks:
      - sahaa_network
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    networks:
      - sahaa_network
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sahaa_network
    restart: always

  auto-labeling-worker:
    build: .
    container_name: auto-labeling-worker
    command: >
      sh -c "celery -A config worker --loglevel=info --queues=queue_one"
    volumes:
      - .:/app
    networks:
      - sahaa_network
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: always

  is-news-worker:
    build: .
    container_name: is-news-worker
    command: >
      sh -c "celery -A config worker --loglevel=info --queues=queue_two"
    volumes:
      - .:/app
    networks:
      - sahaa_network
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: always
    
  news-content-worker:
    build: .
    container_name: news-content-worker
    command: >
      sh -c "celery -A config worker --loglevel=info --queues=queue_three"
    volumes:
      - .:/app
    networks:
      - sahaa_network
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: always


  celery-beat:
    build: .
    container_name: celery-beat
    command: >
      sh -c "celery -A config beat --loglevel=info"
    volumes:
      - .:/app
    networks:
      - sahaa_network
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:

networks:
  sahaa_network:
    external: true
